CREATE_USER_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS telegram_users 
        (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER,
        USERNAME CHAR(50),
        FISRT_NAME CHAR(50),
        LAST_NAME CHAR(50),
        UNIQUE (TELEGRAM_ID)
        )
"""

CREATE_BAN_USER_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS ban_users
        (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER,
        USERNAME CHAR(50),
        COUNT INTEGER,
        UNIQUE (TELEGRAM_ID)
        )
"""
CREAT_ANKETA_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS anketa_users 
        (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER,
        USERNAME CHAR(50),
        BIO TEXT,
        PHOTO TEXT,
        UNIQUE (TELEGRAM_ID)
        )

"""
INSERT_ANKETA_USERS_QUERY = """INSERT OR IGNORE INTO anketa_users VALUES (?,?,?,?,?)"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES (?,?,?,?,?)
"""

SELECT_ALL_USERS_QUERY = """
SELECT * FROM telegram_users
"""
SELECT_ALL_FORM_USERS_QUERY = """
SELECT * FROM anketa_users
"""
SELECT_USER_QUERY = """
SELECT * FROM telegram_users WHERE TELEGRAM_ID = ?
"""
SELECT_BAN_USERS_QUERY = """SELECT * FROM ban_users WHERE TELEGRAM_ID = ?"""

INSERT_BAN_USER_QUERY = """
INSERT OR IGNORE INTO ban_users VALUES(?,?,?,?)
"""

UPDATE_BAN_USER_COUNT_QUERY = """
UPDATE ban_users SET COUNT = COUNT + 1 WHERE TELEGRAM_ID = ?
"""
